export const casesData = [
  {
    id: "C001",
    client: "John Smith",
    type: "Financial",
    priority: "urgent",
    status: "Insights Submitted",
    detective: "Detective Emma Watson",
    date: "1/5/2026",
    insight:
      "Initial investigation reveals suspicious wire transfers totaling $250,000 to offshore accounts. Found discrepancies in ledger entries during October–December period. Recommend forensic accounting audit.",
  },
  {
    id: "C002",
    client: "Sarah Johnson",
    type: "Background Check",
    priority: "medium",
    status: "In Progress",
    detective: "Detective James Bond",
    date: "1/20/2026",
  },
  {
    id: "C003",
    client: "John Smith",
    type: "Asset Recovery",
    priority: "high",
    status: "Report Ready",
    detective: "Detective Emma Watson",
    date: "1/10/2026",
  },
  {
    id: "C004",
    client: "Michael Chen",
    type: "Insurance Fraud",
    priority: "medium",
    status: "Pending",
    detective: "",
    date: "1/25/2026",
  },
  {
    id: "C005",
    client: "Sarah Johnson",
    type: "Missing Person",
    priority: "urgent",
    status: "Assigned",
    detective: "Detective Olivia Martinez",
    date: "1/30/2026",
  },
  {
    id: "C006",
    client: "Emily Davis",
    type: "Workplace Investigation",
    priority: "high",
    status: "Pending",
    detective: "",
    date: "2/5/2026",
  },
  {
    id: "C007",
    client: "David Brown",
    type: "Corporate Investigation",
    priority: "urgent",
    status: "Pending",
    detective: "",
    date: "2/4/2026",
  },
  {
    id: "C008",
    client: "Emily Davis",
    type: "Personal Investigation",
    priority: "medium",
    status: "Pending",
    detective: "",
    date: "2/8/2026",
  },
];